[workspace]
members = [
    "programs/cryptid",
    "programs/middleware/check_recipient",
    "programs/middleware/check_pass",
    "programs/middleware/check_did",
    "programs/middleware/time_delay",
    "programs/middleware/superuser_check_signer"
]
types = "packages/client/idl/src"

[features]
seeds = false
skip-lint = false

[programs.localnet]
cryptid = "cryptJTh61jY5kbUmBEXyc86tBUyueBDrLuNSZWmUcs"
check_recipient = "midcHDoZsxvMmNtUr8howe8MWFrJeHHPbAyJF1nHvyf"
check_pass = "midpT1DeQGnKUjmGbEtUMyugXL5oEBeXU3myBMntkKo"
check_did = "midb3GKX7wF1minPXeDKqGRKCK9NeR8ns9V8BQUMJDr"
time_delay = "midttN2h6G2CBvt1kpnwUsFXM6Gv7gratVwuo2XhSNk"
superuser_check_signer = "midsEy2qfSX1gguxZT3Kv4dGTDisi7iDMAJfSmyG5Y9"

[programs.mainnet]
cryptid = "cryptJTh61jY5kbUmBEXyc86tBUyueBDrLuNSZWmUcs"
check_recipient = "midcHDoZsxvMmNtUr8howe8MWFrJeHHPbAyJF1nHvyf"
check_pass = "midpT1DeQGnKUjmGbEtUMyugXL5oEBeXU3myBMntkKo"
check_did = "midb3GKX7wF1minPXeDKqGRKCK9NeR8ns9V8BQUMJDr"
time_delay = "midttN2h6G2CBvt1kpnwUsFXM6Gv7gratVwuo2XhSNk"
superuser_check_signer = "midsEy2qfSX1gguxZT3Kv4dGTDisi7iDMAJfSmyG5Y9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "didso1Dpqpm4CsiCjzP766BGY89CAdD6ZBL68cRhFPc"
program = "packages/tests/fixtures/sol_did_3.1.1.so"

[[test.genesis]]
address = "gatem74V238djXdzWnJf94Wo1DcnuGkfijbf3AuBhfs"
program = "packages/tests/fixtures/solana_gateway_program.so"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 packages/tests/src/**/*.ts"
